# Generated by Django 4.1.3 on 2022-11-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quizId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
