# Generated by Django 4.1.3 on 2022-12-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_quizid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Allowed',
        ),
    ]
