# Generated by Django 4.1.3 on 2022-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
