# Generated by Django 4.1.3 on 2022-12-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_toalmarks_quiz_totalquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='toalMarks',
            new_name='totalMarks',
        ),
    ]
