# Generated by Django 4.1.3 on 2022-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_quizlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='placeHolder',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=2000),
        ),
    ]
