# Generated by Django 4.1.3 on 2022-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
