# Generated by Django 4.1.3 on 2022-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_quiz_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizName',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
