# Generated by Django 4.1.3 on 2022-12-09 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='currentResponse',
        ),
    ]
