# Generated by Django 4.1.3 on 2022-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_rename_response_currentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='totalTime',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
