# Generated by Django 4.1.3 on 2022-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_totaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
