# Generated by Django 4.1.3 on 2022-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_question_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizEndTime',
            field=models.DateField(blank=True, default='2022-12-12'),
            preserve_default=False,
        ),
    ]
