export const GET_QUIZ_REQUEST = "GET_QUIZ_REQUEST";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const GET_QUIZ_FAIL = "GET_QUIZ_FAIL";
export const GET_QUIZ_RESET = "GET_QUIZ_RESET";

export const SELECTED_QUIZ = "SELECTED_QUIZ";
export const SELECTED_RESET = "SELECTED_RESET";

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";
export const GET_QUESTIONS_RESET = "GET_QUESTIONS_RESET";


export const GET_CORRECT_ANSWERS_REQUEST = "GET_CORRECT_ANSWERS_REQUEST";
export const GET_CORRECT_ANSWERS_SUCCESS = "GET_CORRECT_ANSWERS_SUCCESS";
export const GET_CORRECT_ANSWERS_FAIL = "GET_CORRECT_ANSWERS_FAIL";
export const GET_CORRECT_ANSWERS_RESET = "GET_CORRECT_ANSWERS_RESET";


export const ADD_TOTAL_TIME = "ADD_TOTAL_TIME";

export const ADD_ANSWERED_QUESTIONS = "ADD_ANSWERED_QUESTIONS";
export const REMOVE_ANSWERED_QUESTIONS = "REMOVE_ANSWERED_QUESTIONS";
export const RESET_ANSWERED_QUESTIONS = "RESET_ANSWERED_QUESTIONS";

export const CHECK_CORRECT_ANSWER_REQUEST = "CHECK_CORRECT_ANSWER_REQUEST";
export const CHECK_CORRECT_ANSWER_SUCCESS = "CHECK_CORRECT_ANSWER_SUCCESS";
export const CHECK_CORRECT_ANSWER_FAIL = "CHECK_CORRECT_ANSWER_FAIL";
export const CHECK_CORRECT_ANSWER_RESET = "CHECK_CORRECT_ANSWER_RESET";


export const GET_SAVE_RESPONSE_REQUEST = "GET_SAVE_RESPONSE_REQUEST";
export const GET_SAVE_RESPONSE_SUCCESS = "GET_SAVE_RESPONSE_SUCCESS";
export const GET_SAVE_RESPONSE_FAIL = "GET_SAVE_RESPONSE_FAIL";


export const SAVE_CURRENT_RESPONSE_REQUEST = "SAVE_CURRENT_RESPONSE_REQUEST";
export const SAVE_CURRENT_RESPONSE_SUCCESS = "SAVE_CURRENT_RESPONSE_SUCCESS";
export const SAVE_CURRENT_RESPONSE_FAIL = "SAVE_CURRENT_RESPONSE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
