export const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN"
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN"
export const FAIL_USER_LOGIN = "FAIL_USER_LOGIN"


export const REQUEST_RESET_USER = "REQUEST_RESET_USER"
export const SUCCESS_RESET_USER = "SUCCESS_RESET_USER"
export const FAIL_RESET_USER = "FAIL_RESET_USER"


export const USER_LOGOUT = "USER_LOGOUT"